UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 1, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN-1'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 5, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN-2'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 10, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN-3'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 20, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN-4'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 30, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN-5'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 50, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN-6'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '24:00:00', processing_type_id = 2, processing_type_value = 1, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN24-1'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '24:00:00', processing_type_id = 2, processing_type_value = 5, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN24-2'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '24:00:00', processing_type_id = 2, processing_type_value = 10, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN24-3'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '24:00:00', processing_type_id = 2, processing_type_value = 15, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN24-4'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '24:00:00', processing_type_id = 2, processing_type_value = 30, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN24-5'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '24:00:00', processing_type_id = 2, processing_type_value = 50, param_id = (SELECT id FROM param WHERE name IN ('SNACC-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-SN24-6'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 1, param_id = (SELECT id FROM param WHERE name IN ('RR-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-RR-1'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 10, param_id = (SELECT id FROM param WHERE name IN ('RR-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-RR-2'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 20, param_id = (SELECT id FROM param WHERE name IN ('RR-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-RR-3'));
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00', processing_type_id = 2, processing_type_value = 0.4, param_id = (SELECT id FROM param WHERE name IN ('RR-KGM2')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('PROB-RR-4'));

UPDATE _TABLE_ SET aggregation_id = 4, aggregation_period = '01:00:00', production_type_id = 3, param_id = (SELECT id FROM param WHERE name IN ('FFG-MS')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('FFG2-MS')) AND forecast_period <= '90:00:00';
UPDATE _TABLE_ SET aggregation_id = 4, aggregation_period = '03:00:00', production_type_id = 3, param_id = (SELECT id FROM param WHERE name IN ('FFG-MS')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('FFG2-MS')) AND forecast_period > '90:00:00' and forecast_period <= '144:00:00';
UPDATE _TABLE_ SET aggregation_id = 4, aggregation_period = '06:00:00', production_type_id = 3, param_id = (SELECT id FROM param WHERE name IN ('FFG-MS')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('FFG2-MS')) AND forecast_period > '144:00:00';
UPDATE _TABLE_ SET aggregation_id = 4, aggregation_period = '24:00:00', param_id = (SELECT id FROM param WHERE name IN ('FFG-MS')) WHERE param_id IN (SELECT id FROM param WHERE name IN ('FFG24H-MS'));

UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '01:00:00' WHERE param_id IN (SELECT id FROM param WHERE name IN ('RADSW-WM2', 'RADLW-WM2', 'RADGLO-WM2', 'RTOPLW-WM2', 'RADLWC-WM2', 'RADGLOC-WM2', 'RNETLW-WM2')) AND forecast_period <= '90:00:00';
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '03:00:00' WHERE param_id IN (SELECT id FROM param WHERE name IN ('RADSW-WM2', 'RADLW-WM2', 'RADGLO-WM2', 'RTOPLW-WM2', 'RADLWC-WM2', 'RADGLOC-WM2', 'RNETLW-WM2')) AND forecast_period > '90:00:00' AND forecast_period <= '144:00:00';
UPDATE _TABLE_ SET aggregation_id = 2, aggregation_period = '06:00:00' WHERE param_id IN (SELECT id FROM param WHERE name IN ('RADSW-WM2', 'RADLW-WM2', 'RADGLO-WM2', 'RTOPLW-WM2', 'RADLWC-WM2', 'RADGLOC-WM2', 'RNETLW-WM2')) AND forecast_period > '144:00:00';
