on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]

name: Create container image

jobs:
  call-image-build-workflow:
    uses: fmidev/github-actions-workflows/.github/workflows/imagebuild-workflow.yaml@main
    with:
      image_name: radon
    secrets:
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
