DROP TABLE IF EXISTS grid_data_template;

CREATE OR REPLACE FUNCTION public.radon_version_f()
 RETURNS TEXT
 LANGUAGE plpgsql
 STABLE STRICT SECURITY DEFINER
AS $function$
BEGIN
  RETURN '20241119';
END;
$function$
